# Generated by Django 3.2.3 on 2021-05-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0002_alter_coviddata_clasificacion_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='clasificacion_final',
            field=models.CharField(max_length=200),
        ),
    ]
