# Generated by Django 3.2.3 on 2021-05-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0003_alter_coviddata_clasificacion_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='asma',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='cardiovascular',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='diabetes',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='embarazo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='epoc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='habla_lengua_indig',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='hipertension',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='indigena',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='inmusupr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='intubado',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='neumonia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='obesidad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='otra_com',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='otro_caso',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='renal_cronica',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='tabaquismo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
