# Generated by Django 3.2.3 on 2021-05-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0004_auto_20210531_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='clasificacion_final',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='entidad_nac',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='entidad_res',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='entidad_um',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='id_registro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='migrante',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='municipio_res',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='origen',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='pais_origen',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='resultado_antigeno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='resultado_lab',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='sector',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='tipo_paciente',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='toma_muestra_antigeno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='toma_muestra_lab',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='coviddata',
            name='uci',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
