# Generated by Django 3.2.3 on 2021-05-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_app', '0005_auto_20210531_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='pais_nacionalidad',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
